/**
 * AURA - Git & GitHub Autonomy View
 * Repositories, branch management, conventional commits, automated PRs & CI pipeline.
 */

import React, { useState } from "react";
import {
  CheckCircle2,
  Clock,
  ExternalLink,
  FolderGit2,
  GitBranch,
  GitCommit,
  GitPullRequest,
  Plus,
  ShieldCheck,
  Zap,
} from "lucide-react";
import { GitRepository } from "../types";

interface GitViewProps {
  repository: GitRepository | null;
  onCreateBranch: (name: string) => void;
  onCreatePR: (params: { title: string; description: string; headBranch: string }) => void;
}

export const GitView: React.FC<GitViewProps> = ({ repository, onCreateBranch, onCreatePR }) => {
  const [newBranchName, setNewBranchName] = useState("");
  const [showPRModal, setShowPRModal] = useState(false);
  const [prTitle, setPrTitle] = useState("");
  const [prDesc, setPrDesc] = useState("");

  if (!repository) {
    return (
      <div className="p-12 text-center text-slate-500 font-mono">
        No active Git repository connected. Initialize a goal to spawn a workspace!
      </div>
    );
  }

  const handleBranchSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (newBranchName.trim()) {
      onCreateBranch(newBranchName.trim());
      setNewBranchName("");
    }
  };

  const handlePRSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (prTitle.trim()) {
      onCreatePR({
        title: prTitle.trim(),
        description: prDesc.trim() || "Autonomous PR generated by AURA.",
        headBranch: repository.currentBranch,
      });
      setPrTitle("");
      setPrDesc("");
      setShowPRModal(false);
    }
  };

  return (
    <div className="space-y-6">
      {/* Header Bar */}
      <div className="p-5 rounded-2xl bg-slate-900 border border-slate-800 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center space-x-2 text-xs font-mono text-cyan-400 uppercase tracking-wider font-semibold">
            <FolderGit2 className="w-4 h-4" />
            <span>Autonomous Version Control</span>
          </div>
          <h2 className="text-xl font-bold text-white mt-1">{repository.name}</h2>
          <p className="text-xs text-slate-400 mt-0.5 font-mono">
            Origin: {repository.url} • Default Branch: {repository.defaultBranch}
          </p>
        </div>

        <div className="flex items-center space-x-2">
          <button
            onClick={() => setShowPRModal(true)}
            className="px-4 py-2.5 bg-emerald-500 hover:bg-emerald-400 text-slate-950 font-bold text-xs rounded-xl transition-all flex items-center space-x-2 shadow-lg shrink-0"
          >
            <GitPullRequest className="w-4 h-4" />
            <span>Open Autonomous PR</span>
          </button>
        </div>
      </div>

      {/* Branches & Active Branch Strip */}
      <div className="p-4 rounded-xl bg-slate-900 border border-slate-800 flex flex-col sm:flex-row sm:items-center justify-between gap-3">
        <div className="flex items-center space-x-2 text-xs font-mono">
          <GitBranch className="w-4 h-4 text-cyan-400" />
          <span className="text-slate-400">Current Branch:</span>
          <span className="px-2 py-0.5 rounded bg-cyan-950 border border-cyan-800 text-cyan-300 font-semibold">
            {repository.currentBranch}
          </span>
        </div>

        <form onSubmit={handleBranchSubmit} className="flex items-center space-x-2">
          <input
            type="text"
            value={newBranchName}
            onChange={(e) => setNewBranchName(e.target.value)}
            placeholder="aura/feature-name..."
            className="px-3 py-1.5 bg-slate-950 border border-slate-700 rounded-lg text-xs text-white font-mono placeholder-slate-500 focus:outline-none focus:border-cyan-400"
          />
          <button
            type="submit"
            className="px-3 py-1.5 bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-mono rounded-lg transition-colors"
          >
            + Create Branch
          </button>
        </form>
      </div>

      {/* Two Columns: Pull Requests & Commit Stream */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Pull Requests Panel */}
        <div className="space-y-4">
          <h3 className="text-sm font-bold text-white uppercase font-mono tracking-wider flex items-center space-x-2">
            <GitPullRequest className="w-4 h-4 text-emerald-400" />
            <span>Pull Requests ({repository.pullRequests.length})</span>
          </h3>

          <div className="space-y-3">
            {repository.pullRequests.map((pr) => (
              <div
                key={pr.id}
                className="p-4 rounded-xl bg-slate-900 border border-slate-800 space-y-3"
              >
                <div className="flex items-center justify-between">
                  <div className="flex items-center space-x-2">
                    <span className="font-bold text-sm text-white">#{pr.number}</span>
                    <span className="font-semibold text-sm text-slate-200">{pr.title}</span>
                  </div>
                  <span
                    className={`text-[10px] font-mono px-2 py-0.5 rounded-full font-semibold uppercase ${
                      pr.status === "merged"
                        ? "bg-purple-950/80 border border-purple-800 text-purple-300"
                        : "bg-emerald-950/80 border border-emerald-800 text-emerald-300"
                    }`}
                  >
                    {pr.status}
                  </span>
                </div>

                <p className="text-xs text-slate-400 font-sans">{pr.description}</p>

                <div className="flex items-center space-x-2 text-[11px] font-mono text-slate-500">
                  <span>{pr.headBranch}</span>
                  <span>→</span>
                  <span className="text-cyan-400">{pr.baseBranch}</span>
                </div>

                {/* CI Checks Status */}
                <div className="pt-2 border-t border-slate-800/80 space-y-1.5">
                  <span className="text-[10px] font-mono uppercase text-slate-500 block">CI Checks Pipeline:</span>
                  {pr.ciChecks.map((ci, i) => (
                    <div
                      key={i}
                      className="p-2 rounded bg-slate-950 border border-slate-800/80 flex items-center justify-between text-[11px] font-mono"
                    >
                      <div className="flex items-center space-x-2">
                        {ci.status === "passed" ? (
                          <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400 shrink-0" />
                        ) : (
                          <Clock className="w-3.5 h-3.5 text-cyan-400 shrink-0 animate-spin" />
                        )}
                        <span className="text-slate-300">{ci.name}</span>
                      </div>
                      <span className="text-slate-500">{ci.details}</span>
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Commit History Timeline */}
        <div className="space-y-4">
          <h3 className="text-sm font-bold text-white uppercase font-mono tracking-wider flex items-center space-x-2">
            <GitCommit className="w-4 h-4 text-cyan-400" />
            <span>Autonomous Commit Log ({repository.commits.length})</span>
          </h3>

          <div className="space-y-2 max-h-[500px] overflow-y-auto pr-1">
            {repository.commits.map((c) => (
              <div
                key={c.id}
                className="p-3.5 rounded-xl bg-slate-900 border border-slate-800 flex items-start justify-between text-xs font-mono"
              >
                <div>
                  <div className="flex items-center space-x-2">
                    <span className="px-1.5 py-0.2 rounded bg-slate-950 text-cyan-400 font-bold">
                      {c.hash}
                    </span>
                    <span className="text-white font-medium">{c.message}</span>
                  </div>
                  <div className="text-[11px] text-slate-500 mt-1 flex items-center space-x-3">
                    <span>{c.author}</span>
                    <span>•</span>
                    <span className="text-emerald-400">+{c.additions}</span>
                    <span className="text-rose-400">-{c.deletions}</span>
                    <span>•</span>
                    <span>{new Date(c.timestamp).toLocaleTimeString()}</span>
                  </div>
                </div>

                <span className="text-[10px] px-2 py-0.5 rounded bg-slate-950 text-slate-400 shrink-0 ml-2">
                  {c.branch}
                </span>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Open PR Modal */}
      {showPRModal && (
        <div className="fixed inset-0 bg-black/70 backdrop-blur-sm z-50 flex items-center justify-center p-4">
          <div className="bg-slate-900 border border-slate-800 rounded-2xl max-w-md w-full p-6 space-y-4 shadow-2xl">
            <h3 className="text-lg font-bold text-white flex items-center space-x-2">
              <GitPullRequest className="w-5 h-5 text-emerald-400" />
              <span>Create Autonomous Pull Request</span>
            </h3>

            <form onSubmit={handlePRSubmit} className="space-y-3 text-xs">
              <div>
                <label className="block font-mono text-slate-300 mb-1">Title</label>
                <input
                  type="text"
                  value={prTitle}
                  onChange={(e) => setPrTitle(e.target.value)}
                  placeholder="feat: automated production release"
                  className="w-full px-3 py-2 bg-slate-950 border border-slate-700 rounded-lg text-white font-sans focus:outline-none focus:border-cyan-400"
                  required
                />
              </div>

              <div>
                <label className="block font-mono text-slate-300 mb-1">Description</label>
                <textarea
                  value={prDesc}
                  onChange={(e) => setPrDesc(e.target.value)}
                  placeholder="Automated changes verified by test suite..."
                  rows={3}
                  className="w-full px-3 py-2 bg-slate-950 border border-slate-700 rounded-lg text-white font-sans focus:outline-none focus:border-cyan-400"
                />
              </div>

              <div className="flex justify-end space-x-2 pt-2">
                <button
                  type="button"
                  onClick={() => setShowPRModal(false)}
                  className="px-4 py-2 bg-slate-800 hover:bg-slate-700 text-slate-300 rounded-lg font-semibold"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="px-4 py-2 bg-emerald-500 hover:bg-emerald-400 text-slate-950 rounded-lg font-bold"
                >
                  Submit & Trigger CI
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};
